apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  storageClassName: shared-storage
  accessModes:
    - ReadWriteOnce
