apiVersion: apps/v1
kind: Deployment
metadata:
  name: shawarma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shawarma
      env: stg
      tier: backend
  template:
    metadata:
      name: backend-pod
      labels:
        app: shawarma
        env: stg
        tier: backend
    spec:
     containers:
      - name: backend-container
        image: wrapp:v1
        ports:
        - containerPort: 4433
        resources:
          requests:
            memory: 32Mi
            cpu: 120m
          limits:
            memory: 150Mi
            cpu: 1000m
        livenessProbe:
          httpGet:
            path: /healthyz
            port: 4433
          initialDelaySeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 4433
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shawarma-svc
spec:
  type: NodePort
  selector:
    app: shawarma
  ports:
  - port: 4433
    targetPort: 4433
    nodePort: 31313
  