apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts: # container -> volume pod 
      - name: util-vol-1
        mountPath: /hothaifa
    ports:
      - containerPort: 80
  volumes: # pod -> pvc 
    - name: util-vol-1
      persistentVolumeClaim:
        claimName: utils-pvc
